// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import model_1 from 'C:/bysj/gymsystem-frontend/src/models/member';
import model_2 from 'C:/bysj/gymsystem-frontend/src/.umi/plugin-initialState/@@initialState';

export const models = {
model_1: { namespace: 'member', model: model_1 },
model_2: { namespace: '@@initialState', model: model_2 },
} as const
