version: '3.8'

services:
  # 主反向代理服务
  nginx-proxy:
    image: nginx:1.25-alpine
    container_name: gymsystem-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # 挂载主代理的配置文件 (需在根目录创建此文件)
      - ./nginx-proxy.conf:/etc/nginx/conf.d/default.conf
      # 挂载 Let's Encrypt 生成的 SSL 证书
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - gymsystem-network
    depends_on:
      - frontend
      - backend

  # 后端服务
  backend:
    container_name: gymsystem-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    environment:
      # Spring Boot 生产环境配置
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - gymsystem-network

  # 前端服务
  frontend:
    container_name: gymsystem-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - backend
    networks:
      - gymsystem-network

# 定义网络
networks:
  gymsystem-network:
    driver: bridge