// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import SmileOutlined from 'D:/MyCode/用户中心管理/user-center-front/usercenter/node_modules/@ant-design/icons/es/icons/SmileOutlined';
import CrownOutlined from 'D:/MyCode/用户中心管理/user-center-front/usercenter/node_modules/@ant-design/icons/es/icons/CrownOutlined';
import TableOutlined from 'D:/MyCode/用户中心管理/user-center-front/usercenter/node_modules/@ant-design/icons/es/icons/TableOutlined';
export default { SmileOutlined, CrownOutlined, TableOutlined };
