// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import CrownOutlined from 'D:/MyCode/Frontend/gymsystem-frontend/node_modules/@ant-design/icons/es/icons/CrownOutlined';
import UserOutlined from 'D:/MyCode/Frontend/gymsystem-frontend/node_modules/@ant-design/icons/es/icons/UserOutlined';
import ReadOutlined from 'D:/MyCode/Frontend/gymsystem-frontend/node_modules/@ant-design/icons/es/icons/ReadOutlined';
import AppstoreOutlined from 'D:/MyCode/Frontend/gymsystem-frontend/node_modules/@ant-design/icons/es/icons/AppstoreOutlined';
import CalendarOutlined from 'D:/MyCode/Frontend/gymsystem-frontend/node_modules/@ant-design/icons/es/icons/CalendarOutlined';
import ScheduleOutlined from 'D:/MyCode/Frontend/gymsystem-frontend/node_modules/@ant-design/icons/es/icons/ScheduleOutlined';
import CreditCardOutlined from 'D:/MyCode/Frontend/gymsystem-frontend/node_modules/@ant-design/icons/es/icons/CreditCardOutlined';
import TeamOutlined from 'D:/MyCode/Frontend/gymsystem-frontend/node_modules/@ant-design/icons/es/icons/TeamOutlined';
import ToolOutlined from 'D:/MyCode/Frontend/gymsystem-frontend/node_modules/@ant-design/icons/es/icons/ToolOutlined';
import ShoppingOutlined from 'D:/MyCode/Frontend/gymsystem-frontend/node_modules/@ant-design/icons/es/icons/ShoppingOutlined';
import TransactionOutlined from 'D:/MyCode/Frontend/gymsystem-frontend/node_modules/@ant-design/icons/es/icons/TransactionOutlined';
export default { CrownOutlined, UserOutlined, ReadOutlined, AppstoreOutlined, CalendarOutlined, ScheduleOutlined, CreditCardOutlined, TeamOutlined, ToolOutlined, ShoppingOutlined, TransactionOutlined };
