// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import CrownOutlined from 'C:/bysj/gymsystem-frontend/node_modules/@ant-design/icons/es/icons/CrownOutlined';
import UserOutlined from 'C:/bysj/gymsystem-frontend/node_modules/@ant-design/icons/es/icons/UserOutlined';
import TeamOutlined from 'C:/bysj/gymsystem-frontend/node_modules/@ant-design/icons/es/icons/TeamOutlined';
import BookOutlined from 'C:/bysj/gymsystem-frontend/node_modules/@ant-design/icons/es/icons/BookOutlined';
import ShoppingOutlined from 'C:/bysj/gymsystem-frontend/node_modules/@ant-design/icons/es/icons/ShoppingOutlined';
import ToolOutlined from 'C:/bysj/gymsystem-frontend/node_modules/@ant-design/icons/es/icons/ToolOutlined';
import ShoppingCartOutlined from 'C:/bysj/gymsystem-frontend/node_modules/@ant-design/icons/es/icons/ShoppingCartOutlined';
export default { CrownOutlined, UserOutlined, TeamOutlined, BookOutlined, ShoppingOutlined, ToolOutlined, ShoppingCartOutlined };
